name: Automatic workflow

on:
  push:
    branches:
      - main

jobs:
  checkdir:
    runs-on: self-hosted
    steps:
      - name: Run tests against project 
        run: |
          cd /var/www/html
          /usr/bin/php /var/www/html/artisan test
