name: Automatic workflow

on:
  push:
    branches:
      - main

jobs:
  checkdir:
    runs-on: self-hosted
    steps:
      - name: Check root directory
        run: |
          /usr/bin/php /var/www/html/artisan test
