name: Automatic workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    types:
      - completed
jobs:
  update:
    runs-on: self-hosted
    steps: 
      - name: update project
        run: |
          cd /var/www/html/
          git reset --hard origin/main
          git pull
          composer update
          npm install
          npm run build
          php artisan migrate --force
  running_test:
    needs: [update]
    runs-on: self-hosted
    steps:
      - name: Run tests against project 
        run: |
          cd /var/www/html
          /usr/bin/php /var/www/html/artisan test
