name: Automatic workflow

on:
  push:
    branches:
      - main
    types:
      - completed
jobs:
  update:
    runs-on: self-hosted
    steps: 
      - name: update project
        run: |
          cd /var/www/html/
          git pull
          composer update
          npm install
          npm run build
          php artisan migrate
  running_test:
    runs-on: self-hosted
    steps:
      - name: Run tests against project 
        run: |
          cd /var/www/html
          /usr/bin/php /var/www/html/artisan test
